import { mountIcons } from './icons.js';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;},opt=(text,value)=>{const n=el('option',text);n.value=value;return n;};
export function createAdminSeries({api,write,message}){
 let selected=0,offset=0,docOffset=0,items=[],busy=false,version=0;
 $('series-view').innerHTML=`<div class="admin-heading"><h1>系列书籍</h1><button id="as-new" class="button" type="button">新建系列</button></div><div class="admin-series-layout"><nav id="as-nav" aria-label="书籍系列"></nav><div><form id="as-form" class="series-admin-form"><label>系列名称<input id="as-name" required maxlength="120"></label><label>简介<textarea id="as-description" rows="2" maxlength="2000"></textarea></label><label>系列顺序<input id="as-order" type="number" min="0" max="1000000" value="0" required></label><div class="admin-actions"><button class="button primary">保存系列</button><button id="as-delete" class="button" type="button">删除系列</button></div></form><section id="as-bindings"><h2>关联文献</h2><div class="series-admin-associate"><select id="as-folder" aria-label="文献目录"></select><button id="as-folder-add" class="button" type="button">关联整个目录</button></div><form id="as-search" class="series-search"><input id="as-query" type="search" placeholder="搜索文献库书名" aria-label="搜索文献库"><button class="button">搜索</button></form><div class="series-admin-associate"><select id="as-document" aria-label="选择书籍"></select><button id="as-book-add" class="button" type="button">添加书籍</button></div><div class="series-pager"><button id="as-doc-prev" class="button compact" type="button">上一页</button><span id="as-doc-page"></span><button id="as-doc-next" class="button compact" type="button">下一页</button></div><div id="as-books"></div><div class="series-pager"><button id="as-prev" class="button compact" type="button">上一页</button><span id="as-page"></span><button id="as-next" class="button compact" type="button">下一页</button></div></section></div></div>`;
 async function action(work){if(busy)return;busy=true;$('series-view').querySelectorAll('button').forEach(b=>b.disabled=true);try{await work();message('已保存。');}catch(e){message(e.message,true);}finally{busy=false;try{await load();}catch(e){message(e.message,true);}}}
 function edit(s){selected=s?.id||0;offset=0;$('as-name').value=s?.name||'';$('as-description').value=s?.description||'';$('as-order').value=s?.sort_order||0;$('as-delete').disabled=!selected;$('as-bindings').hidden=!selected;for(const b of $('as-nav').children)b.setAttribute('aria-current',Number(b.dataset.series)===selected?'page':'false');}
 async function documents(){const mine=++version;const body=await api('/api/admin/documents?'+new URLSearchParams({q:$('as-query').value.trim(),collection:$('as-folder').value,offset:docOffset}));if(mine!==version)return;$('as-document').replaceChildren(opt('请选择文献',''),...body.documents.map(d=>opt(d.title,d.id)));$('as-book-add').disabled=busy||!$('as-document').value;$('as-doc-prev').disabled=docOffset===0;$('as-doc-next').disabled=body.documents.length<20;$('as-doc-page').textContent='第 '+(docOffset/20+1)+' 页';}
 async function books(){if(!selected)return;const id=selected,body=await api(`/api/admin/series/${id}?offset=${offset}`);if(id!==selected)return;const list=$('as-books');list.replaceChildren();for(const doc of body.books){const row=el('article',null,'series-book'),info=el('div');info.append(el('h3',doc.title),el('p',doc.authors||'','series-author'));const actions=el('div',null,'series-member-actions'),input=el('input');input.type='number';input.min=0;input.max=1000000;input.value=doc.sort_order;input.setAttribute('aria-label','书籍顺序 '+doc.title);const save=el('button','保存顺序','button compact');save.type='button';save.onclick=()=>action(()=>write(`/api/admin/series/${id}/books/${doc.id}`,{sort_order:Number(input.value)},'PATCH'));const remove=el('button','移除','button compact');remove.type='button';remove.onclick=()=>action(()=>write(`/api/admin/series/${id}/books/${doc.id}`,{},'DELETE'));actions.append(input,save,remove);row.append(info,actions);list.append(row);}if(!body.books.length)list.append(el('p','暂无书籍，可关联文献目录或单独添加。','admin-empty'));$('as-prev').disabled=offset===0;$('as-next').disabled=body.books.length<20;$('as-page').textContent='第 '+(offset/20+1)+' 页';}
 async function load(){const [body,archive]=await Promise.all([api('/api/admin/series'),api('/api/admin/collections')]);items=body.series;const nav=$('as-nav');nav.replaceChildren();for(const s of items){const b=el('button',s.name+' · '+s.book_count,'button');b.type='button';b.dataset.series=s.id;b.onclick=async()=>{if(busy)return;edit(s);await books().catch(e=>message(e.message,true));};nav.append(b);}if(!selected&&items.length)selected=items[0].id;edit(items.find(s=>s.id===selected));const previous=$('as-folder').value,names=f=>{const a=[],seen=new Set();while(f&&!seen.has(f.id)){seen.add(f.id);a.unshift(f.name);f=archive.collections.find(x=>x.id===f.parent_id);}return a.join(' / ');};$('as-folder').replaceChildren(opt('全部文献',''),...archive.collections.map(f=>opt(names(f),f.id)));$('as-folder').value=previous||'';if($('as-folder').selectedIndex<0)$('as-folder').value='';$('series-view').querySelectorAll('button').forEach(b=>b.disabled=false);$('as-delete').disabled=!selected;$('as-folder-add').disabled=!selected||!$('as-folder').value;await Promise.all([books(),documents()]);mountIcons();}
 $('as-new').onclick=()=>{edit(null);$('as-name').focus();};$('as-form').onsubmit=e=>{e.preventDefault();action(async()=>{const body={name:$('as-name').value.trim(),description:$('as-description').value.trim(),sort_order:Number($('as-order').value)},result=await write('/api/admin/series'+(selected?'/'+selected:''),body,selected?'PATCH':'POST');if(result.id)selected=result.id;});};
 $('as-delete').onclick=()=>{if(!selected||!confirm('删除这个系列？仅移除系列及关联，文献、文件和阅读笔记保留。'))return;action(async()=>{await write('/api/admin/series/'+selected,{},'DELETE');selected=0;});};
 $('as-folder').onchange=()=>{docOffset=0;$('as-folder-add').disabled=!$('as-folder').value;documents().catch(e=>message(e.message,true));};$('as-folder-add').onclick=()=>action(()=>write(`/api/admin/series/${selected}/books`,{collection_id:Number($('as-folder').value)}));
 $('as-search').onsubmit=e=>{e.preventDefault();docOffset=0;documents().catch(e=>message(e.message,true));};$('as-document').onchange=()=>$('as-book-add').disabled=!$('as-document').value;$('as-book-add').onclick=()=>action(()=>write(`/api/admin/series/${selected}/books`,{document_id:Number($('as-document').value)}));
 for(const [id,delta]of [['as-doc-prev',-20],['as-doc-next',20]])$(id).onclick=()=>{docOffset=Math.max(0,docOffset+delta);documents().catch(e=>message(e.message,true));};for(const [id,delta]of [['as-prev',-20],['as-next',20]])$(id).onclick=()=>{offset=Math.max(0,offset+delta);books().catch(e=>message(e.message,true));};return {load};
}
