import { mountIcons } from './icons.js';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const errors={ai_not_configured:'请先设置个人 API，或联系管理员启用默认 API。',ai_invalid_url:'请输入 OpenAI 兼容接口的公网 HTTPS 地址。',ai_invalid_settings:'请检查 API 地址、模型和密钥。',ai_recommendation_invalid:'模型返回了无效书目，请重试或更换模型。',series_empty:'所选系列还没有书籍，请先由管理员关联文献。',series_changed:'书目已更新，请重新推荐。',ai_busy:'AI 正在处理其他请求，请稍后重试。',ai_daily_limit:'默认 API 今日额度已用完，可以切换个人 API。',ai_provider_auth:'API 密钥无效，请检查设置。',ai_provider_limit:'服务商额度不足，请检查账户。',ai_connection_failed:'连接模型失败或等待超时，请检查 API 后重试。'};
export function createSeries({api,write}){
 let generation=0,selected=0,offset=0,reading=false,stopReader=null,busy=false;
 $('series-view').innerHTML=`<div class="series-heading"><a class="back-link" href="#/">← 应用工作台</a><h1>系列书籍</h1></div><section class="series-recommender"><div class="series-ai-heading"><h2><span data-icon="spark" aria-hidden="true"></span>AI 教材推荐</h2><div><select id="series-ai-source" aria-label="AI 来源"><option value="default">管理员默认 API</option><option value="custom">我的 API</option></select><button id="series-api-open" class="button compact" type="button">API 设置</button></div></div><form id="series-ai-form"><textarea id="series-requirement" required maxlength="12000" rows="3" aria-label="学习需求" placeholder="例如：学过数学分析和线性代数，想系统学习泛函分析，推荐适合入门到进阶的书籍。"></textarea><div class="series-ai-actions"><select id="series-ai-scope" aria-label="推荐范围"></select><button id="series-recommend" class="button primary"><span data-icon="spark" aria-hidden="true"></span>推荐教材</button></div></form><p id="series-ai-status" role="status" aria-live="polite"></p><div id="series-ai-results"></div></section><div id="series-catalog"></div><p id="series-status" role="status"></p><dialog id="series-api-dialog"><form id="series-api-form"><h2>我的 API</h2><label>API 地址<input id="series-api-url" type="url" required placeholder="https://example.com/v1"></label><label>模型<input id="series-api-model" required maxlength="200"></label><label>密钥<input id="series-api-key" type="password" autocomplete="off" placeholder="留空保留已保存密钥"></label><p id="series-api-status" role="status"></p><div class="series-ai-actions"><button class="button primary">保存并使用</button><button id="series-api-close" class="button" type="button">关闭</button></div></form></dialog>`;
 const friendly=e=>errors[e.code]||e.message;
 function readLink(doc,label='开始阅读'){const a=el('a',label,'button compact');a.href=`#/series/read/${doc.id}?series=${selected||''}`;return a;}
 function bookRow(doc,reason){const row=el('article',null,'series-book'),info=el('div');info.append(el('h3',doc.title));if(doc.authors)info.append(el('p',doc.authors,'series-author'));if(reason)info.append(el('p',reason,'series-reason'));row.append(info,readLink(doc));return row;}
 function close(){generation++;$('series-api-dialog').close();if(stopReader)stopReader();stopReader=null;if(reading){$('reader-view').hidden=true;document.body.classList.remove('reading-page');}reading=false;}
 async function navigate(hash){close();const version=generation,parts=hash.split('?'),path=parts[0],p=new URLSearchParams(parts[1]||''),match=path.match(/^#\/series\/read\/(\d+)$/);reading=!!match;$('series-view').hidden=reading;
  if(match){document.body.classList.add('reading-page');$('reader-view').hidden=false;try{const reader=await import('./reader.js');if(version!==generation)return;const c=reader.openReader(Number(match[1]),{api,write,basePath:'/api/library/documents',backHref:p.get('series')?'#/series/'+p.get('series'):'#/series',backLabel:'← 返回系列书籍'});stopReader=c.close;await c.ready;}catch(e){if(version===generation)$('reader-status').textContent=friendly(e);}return;}
  selected=Number(path.match(/^#\/series\/(\d+)$/)?.[1]||0);offset=Math.max(0,Number(p.get('page')||1)-1)*20;if(!Number.isSafeInteger(offset))offset=0;$('series-status').textContent='正在加载…';
  try{const body=await api('/api/series');if(version!==generation)return;const scope=$('series-ai-scope');scope.replaceChildren();for(const s of [{id:'',name:'全部系列'},...body.series]){const o=el('option',s.name);o.value=s.id;scope.append(o);}scope.value=selected||'';const list=$('series-catalog');list.replaceChildren();
   if(selected){const detail=await api(`/api/series/${selected}?offset=${offset}&q=${encodeURIComponent(p.get('q')||'')}`);if(version!==generation)return;const heading=el('div',null,'series-detail-heading'),back=el('a','← 全部系列','back-link');back.href='#/series';heading.append(back,el('h2',detail.series.name));if(detail.series.description)heading.append(el('p',detail.series.description));list.append(heading);const form=el('form',null,'series-search'),input=el('input');input.type='search';input.placeholder='搜索本系列书籍';input.setAttribute('aria-label','搜索本系列');input.value=p.get('q')||'';const search=el('button','搜索','button');form.append(input,search);form.addEventListener('submit',e=>{e.preventDefault();location.hash=`#/series/${selected}?q=${encodeURIComponent(input.value.trim())}`;});list.append(form);for(const doc of detail.books)list.append(bookRow(doc));if(!detail.books.length)list.append(el('p','暂无书籍','muted'));const pager=el('div',null,'series-pager');for(const [text,delta]of [['上一页',-1],['下一页',1]]){const b=el('button',text,'button compact');b.disabled=delta<0?offset===0:detail.books.length<20;b.onclick=()=>location.hash=`#/series/${selected}?page=${offset/20+1+delta}&q=${encodeURIComponent(p.get('q')||'')}`;pager.append(b);}list.append(pager);
   }else{const grid=el('div',null,'series-grid');for(const [i,s]of body.series.entries()){const card=el('a',null,'series-card series-color-'+i%6);card.href='#/series/'+s.id;card.append(el('span',s.name.match(/\(([^)]+)\)/)?.[1]||(/SMM|UTM/.exec(s.name)?.[0])||(s.name==='Lecture Notes in Mathematics'?'LNM':s.name==='London Mathematical Society Student Texts'?'LMS':'系列'),'series-monogram'),el('h2',s.name),el('span',s.book_count+' 本书籍','series-count'));if(s.description)card.append(el('p',s.description));grid.append(card);}list.append(grid);if(!body.series.length)list.append(el('p','管理员尚未添加系列。','muted'));}
   $('series-status').textContent='';mountIcons();
  }catch(e){if(version===generation)$('series-status').textContent=friendly(e);}
 }
 $('series-ai-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const version=generation,fields=[...e.currentTarget.elements];fields.forEach(n=>n.disabled=true);$('series-ai-status').textContent='正在根据书目匹配教材…';$('series-ai-results').replaceChildren();
  try{const result=await write('/api/series/recommend',{source:$('series-ai-source').value,requirement:$('series-requirement').value.trim(),series_id:Number($('series-ai-scope').value)||null});if(version!==generation)return;$('series-ai-results').append(el('p',result.summary,'series-summary'));for(const doc of result.books)$('series-ai-results').append(bookRow(doc,doc.reason));$('series-ai-status').textContent=result.books.length?'':'当前书目没有适合的推荐。';}catch(error){if(version===generation)$('series-ai-status').textContent=friendly(error);}finally{busy=false;fields.forEach(n=>n.disabled=false);}
 });
 $('series-api-open').onclick=async()=>{try{const settings=await api('/api/ai/settings');$('series-ai-source').value=settings.source;$('series-api-url').value=settings.custom.base_url||'';$('series-api-model').value=settings.custom.model||'';$('series-api-key').value='';$('series-api-status').textContent=settings.custom.has_key?'密钥已保存。':'';$('series-api-dialog').showModal();}catch(e){$('series-ai-status').textContent=friendly(e);}};
 $('series-api-close').onclick=()=>$('series-api-dialog').close();$('series-api-form').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{await write('/api/ai/settings',{source:'custom',enabled:true,base_url:$('series-api-url').value.trim(),model:$('series-api-model').value.trim(),api_key:$('series-api-key').value.trim()},'PUT');$('series-ai-source').value='custom';$('series-api-key').value='';$('series-api-dialog').close();$('series-ai-status').textContent='个人 API 已保存。';}catch(error){$('series-api-status').textContent=friendly(error);}finally{button.disabled=false;}};
 mountIcons();return {navigate,close};
}
