BEGIN;
INSERT OR IGNORE INTO learning_directions VALUES('analysis','分析','极限、函数与变化',1,0);
INSERT OR IGNORE INTO learning_questions VALUES('analysis',0,'如何严格理解极限、连续与收敛？');
INSERT OR IGNORE INTO learning_questions VALUES('analysis',1,'如何研究函数及函数空间？');
INSERT OR IGNORE INTO learning_questions VALUES('analysis',2,'如何判断微分方程的解是否存在、唯一与稳定？');
INSERT OR IGNORE INTO learning_directions VALUES('geometry-topology','几何与拓扑','空间、形状与曲率',1,1);
INSERT OR IGNORE INTO learning_questions VALUES('geometry-topology',0,'如何描述空间的形状与结构？');
INSERT OR IGNORE INTO learning_questions VALUES('geometry-topology',1,'曲率如何影响空间的性质？');
INSERT OR IGNORE INTO learning_questions VALUES('geometry-topology',2,'如何区分和分类不同的空间？');
INSERT OR IGNORE INTO learning_directions VALUES('algebra','代数','运算、结构与对称',1,2);
INSERT OR IGNORE INTO learning_questions VALUES('algebra',0,'如何研究运算与代数结构？');
INSERT OR IGNORE INTO learning_questions VALUES('algebra',1,'如何描述和理解对称性？');
INSERT OR IGNORE INTO learning_questions VALUES('algebra',2,'如何分类与表示代数结构？');
INSERT OR IGNORE INTO learning_directions VALUES('number-theory','数论','整数、素数与方程',0,3);
INSERT OR IGNORE INTO learning_questions VALUES('number-theory',0,'素数如何分布？');
INSERT OR IGNORE INTO learning_questions VALUES('number-theory',1,'整数方程何时有解？');
INSERT OR IGNORE INTO learning_questions VALUES('number-theory',2,'整数的算术结构如何推广？');
INSERT OR IGNORE INTO learning_directions VALUES('probability-statistics','概率与统计','随机性、规律与推断',0,4);
INSERT OR IGNORE INTO learning_questions VALUES('probability-statistics',0,'如何描述随机现象？');
INSERT OR IGNORE INTO learning_questions VALUES('probability-statistics',1,'大量随机事件会呈现什么规律？');
INSERT OR IGNORE INTO learning_questions VALUES('probability-statistics',2,'如何从数据推断总体与不确定性？');
INSERT OR IGNORE INTO learning_directions VALUES('computational','计算数学与数值方法','近似、误差与计算',0,5);
INSERT OR IGNORE INTO learning_questions VALUES('computational',0,'如何求出数学问题的数值解？');
INSERT OR IGNORE INTO learning_questions VALUES('computational',1,'如何控制误差与数值稳定性？');
INSERT OR IGNORE INTO learning_questions VALUES('computational',2,'如何设计高效可靠的计算方法？');
INSERT OR IGNORE INTO learning_directions VALUES('optimization','优化与数学建模','决策、约束与模型',0,6);
INSERT OR IGNORE INTO learning_questions VALUES('optimization',0,'如何在约束下寻找最优解？');
INSERT OR IGNORE INTO learning_questions VALUES('optimization',1,'如何把实际问题转化为数学模型？');
INSERT OR IGNORE INTO learning_questions VALUES('optimization',2,'如何判断模型与算法的有效性？');
INSERT OR IGNORE INTO learning_directions VALUES('discrete-foundations','离散数学与数学基础','组合、逻辑与证明',0,7);
INSERT OR IGNORE INTO learning_questions VALUES('discrete-foundations',0,'如何研究离散结构与组合关系？');
INSERT OR IGNORE INTO learning_questions VALUES('discrete-foundations',1,'数学命题如何得到严格证明？');
INSERT OR IGNORE INTO learning_questions VALUES('discrete-foundations',2,'哪些问题可以被算法解决？');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(1,'analysis','Understanding Analysis','Stephen Abbott','基础入门','微积分与基本证明方法',1,'https://link.springer.com/book/10.1007/978-1-4939-2712-8');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(2,'analysis','Measure, Integration & Real Analysis','Sheldon Axler','核心理论','本科实分析、线性代数',2,'https://measure.axler.net/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(3,'analysis','Functional Analysis, Sobolev Spaces and Partial Differential Equations','Haim Brezis','进阶学习','测度与积分、赋范空间基础',3,'https://link.springer.com/book/10.1007/978-0-387-70914-7');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(4,'geometry-topology','Elementary Differential Geometry','Andrew Pressley','基础入门','多元微积分、线性代数',4,'https://link.springer.com/book/10.1007/978-1-84882-891-9');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(5,'geometry-topology','Introduction to Smooth Manifolds','John M. Lee','核心理论','点集拓扑、多元微积分与证明方法',5,'https://link.springer.com/book/10.1007/978-1-4419-9982-5');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(6,'geometry-topology','Introduction to Riemannian Manifolds','John M. Lee','进阶学习','光滑流形与张量基础',6,'https://link.springer.com/book/10.1007/978-3-319-91755-9');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(7,'algebra','Linear Algebra Done Right','Sheldon Axler','基础入门','基本证明方法；适合作为线性代数第二门课程',7,'https://linear.axler.net/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(8,'algebra','Abstract Algebra: Theory and Applications','Thomas W. Judson','核心理论','线性代数、集合与证明方法',8,'https://scholarworks.sfasu.edu/ebooks/23/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(9,'algebra','Representation Theory: A First Course','William Fulton, Joe Harris','进阶学习','群论、线性代数；后半部分需要李代数基础',9,'https://link.springer.com/book/10.1007/978-1-4612-0979-9');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(10,'number-theory','Elementary Number Theory','Gareth A. Jones, J. Mary Jones','基础入门','整数运算与基本证明方法',10,'https://link.springer.com/book/10.1007/978-1-4471-0613-5');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(11,'number-theory','A Classical Introduction to Modern Number Theory','Kenneth Ireland, Michael Rosen','核心理论','初等数论、群环域基础',11,'https://link.springer.com/book/10.1007/978-1-4757-1779-2');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(12,'probability-statistics','Introduction to Probability','Joseph K. Blitzstein, Jessica Hwang','基础入门','微积分与基础组合计数',12,'https://probabilitybook.net/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(13,'probability-statistics','Probability: Theory and Examples','Rick Durrett','进阶学习','概率基础、测度与积分',13,'https://www.cambridge.org/core/books/probability/DD9A1907F810BB14CCFF022CDFC5677A');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(14,'computational','An Introduction to Numerical Analysis','Endre Süli, David F. Mayers','基础入门','微积分、线性代数与基础编程',14,'https://www.cambridge.org/core/books/an-introduction-to-numerical-analysis/FD8BCAD7FE68002E2179DFF68B8B7237');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(15,'computational','Numerical Linear Algebra','Lloyd N. Trefethen, David Bau III','核心理论','线性代数、数值误差基础',15,'https://epubs.siam.org/doi/book/10.1137/1.9780898719574');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(16,'optimization','Introduction to Applied Linear Algebra: Vectors, Matrices, and Least Squares','Stephen Boyd, Lieven Vandenberghe','基础入门','基础代数与向量运算',16,'https://web.stanford.edu/~boyd/vmls/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(17,'optimization','Convex Optimization','Stephen Boyd, Lieven Vandenberghe','核心理论','线性代数、多元微积分',17,'https://web.stanford.edu/~boyd/cvxbook/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(18,'discrete-foundations','Discrete Mathematics: An Open Introduction','Oscar Levin','基础入门','高中代数与基本逻辑',18,'https://discrete.openmathbooks.org/dmoi3.html');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(19,'discrete-foundations','Graph Theory','Reinhard Diestel','进阶学习','基础图论与严格证明方法',19,'https://diestel-graph-theory.com/');
COMMIT;
