BEGIN;
INSERT OR IGNORE INTO learning_directions VALUES('analysis','分析','极限、函数与变化',1,0);
INSERT OR IGNORE INTO learning_questions VALUES('analysis',0,'如何严格理解极限、连续与收敛？');
INSERT OR IGNORE INTO learning_questions VALUES('analysis',1,'如何研究函数及函数空间？');
INSERT OR IGNORE INTO learning_questions VALUES('analysis',2,'如何判断微分方程的解是否存在、唯一与稳定？');
INSERT OR IGNORE INTO learning_directions VALUES('geometry-topology','几何与拓扑','空间、形状与曲率',1,1);
INSERT OR IGNORE INTO learning_questions VALUES('geometry-topology',0,'如何描述空间的形状与结构？');
INSERT OR IGNORE INTO learning_questions VALUES('geometry-topology',1,'曲率如何影响空间的性质？');
INSERT OR IGNORE INTO learning_questions VALUES('geometry-topology',2,'如何区分和分类不同的空间？');
INSERT OR IGNORE INTO learning_directions VALUES('algebra','代数','运算、结构与对称',1,2);
INSERT OR IGNORE INTO learning_questions VALUES('algebra',0,'如何研究运算与代数结构？');
INSERT OR IGNORE INTO learning_questions VALUES('algebra',1,'如何描述和理解对称性？');
INSERT OR IGNORE INTO learning_questions VALUES('algebra',2,'如何分类与表示代数结构？');
INSERT OR IGNORE INTO learning_directions VALUES('number-theory','数论','整数、素数与方程',0,3);
INSERT OR IGNORE INTO learning_questions VALUES('number-theory',0,'素数如何分布？');
INSERT OR IGNORE INTO learning_questions VALUES('number-theory',1,'整数方程何时有解？');
INSERT OR IGNORE INTO learning_questions VALUES('number-theory',2,'整数的算术结构如何推广？');
INSERT OR IGNORE INTO learning_directions VALUES('probability-statistics','概率与统计','随机性、规律与推断',0,4);
INSERT OR IGNORE INTO learning_questions VALUES('probability-statistics',0,'如何描述随机现象？');
INSERT OR IGNORE INTO learning_questions VALUES('probability-statistics',1,'大量随机事件会呈现什么规律？');
INSERT OR IGNORE INTO learning_questions VALUES('probability-statistics',2,'如何从数据推断总体与不确定性？');
INSERT OR IGNORE INTO learning_directions VALUES('computational','计算数学与数值方法','近似、误差与计算',0,5);
INSERT OR IGNORE INTO learning_questions VALUES('computational',0,'如何求出数学问题的数值解？');
INSERT OR IGNORE INTO learning_questions VALUES('computational',1,'如何控制误差与数值稳定性？');
INSERT OR IGNORE INTO learning_questions VALUES('computational',2,'如何设计高效可靠的计算方法？');
INSERT OR IGNORE INTO learning_directions VALUES('optimization','优化与数学建模','决策、约束与模型',0,6);
INSERT OR IGNORE INTO learning_questions VALUES('optimization',0,'如何在约束下寻找最优解？');
INSERT OR IGNORE INTO learning_questions VALUES('optimization',1,'如何把实际问题转化为数学模型？');
INSERT OR IGNORE INTO learning_questions VALUES('optimization',2,'如何判断模型与算法的有效性？');
INSERT OR IGNORE INTO learning_directions VALUES('discrete-foundations','离散数学与数学基础','组合、逻辑与证明',0,7);
INSERT OR IGNORE INTO learning_questions VALUES('discrete-foundations',0,'如何研究离散结构与组合关系？');
INSERT OR IGNORE INTO learning_questions VALUES('discrete-foundations',1,'数学命题如何得到严格证明？');
INSERT OR IGNORE INTO learning_questions VALUES('discrete-foundations',2,'哪些问题可以被算法解决？');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(1,'analysis','Understanding Analysis','Stephen Abbott','基础入门','微积分与基本证明方法',1,'https://link.springer.com/book/10.1007/978-1-4939-2712-8');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(2,'analysis','Measure, Integration & Real Analysis','Sheldon Axler','核心理论','本科实分析、线性代数',2,'https://measure.axler.net/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(3,'analysis','Functional Analysis, Sobolev Spaces and Partial Differential Equations','Haim Brezis','进阶学习','测度与积分、赋范空间基础',3,'https://link.springer.com/book/10.1007/978-0-387-70914-7');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(4,'geometry-topology','Elementary Differential Geometry','Andrew Pressley','基础入门','多元微积分、线性代数',4,'https://link.springer.com/book/10.1007/978-1-84882-891-9');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(5,'geometry-topology','Introduction to Smooth Manifolds','John M. Lee','核心理论','点集拓扑、多元微积分与证明方法',5,'https://link.springer.com/book/10.1007/978-1-4419-9982-5');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(6,'geometry-topology','Introduction to Riemannian Manifolds','John M. Lee','进阶学习','光滑流形与张量基础',6,'https://link.springer.com/book/10.1007/978-3-319-91755-9');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(7,'algebra','Linear Algebra Done Right','Sheldon Axler','基础入门','基本证明方法；适合作为线性代数第二门课程',7,'https://linear.axler.net/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(8,'algebra','Abstract Algebra: Theory and Applications','Thomas W. Judson','核心理论','线性代数、集合与证明方法',8,'https://scholarworks.sfasu.edu/ebooks/23/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(9,'algebra','Representation Theory: A First Course','William Fulton, Joe Harris','进阶学习','群论、线性代数；后半部分需要李代数基础',9,'https://link.springer.com/book/10.1007/978-1-4612-0979-9');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(10,'number-theory','Elementary Number Theory','Gareth A. Jones, J. Mary Jones','基础入门','整数运算与基本证明方法',10,'https://link.springer.com/book/10.1007/978-1-4471-0613-5');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(11,'number-theory','A Classical Introduction to Modern Number Theory','Kenneth Ireland, Michael Rosen','核心理论','初等数论、群环域基础',11,'https://link.springer.com/book/10.1007/978-1-4757-1779-2');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(12,'probability-statistics','Introduction to Probability','Joseph K. Blitzstein, Jessica Hwang','基础入门','微积分与基础组合计数',12,'https://probabilitybook.net/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(13,'probability-statistics','Probability: Theory and Examples','Rick Durrett','进阶学习','概率基础、测度与积分',13,'https://www.cambridge.org/core/books/probability/DD9A1907F810BB14CCFF022CDFC5677A');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(14,'computational','An Introduction to Numerical Analysis','Endre Süli, David F. Mayers','基础入门','微积分、线性代数与基础编程',14,'https://www.cambridge.org/core/books/an-introduction-to-numerical-analysis/FD8BCAD7FE68002E2179DFF68B8B7237');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(15,'computational','Numerical Linear Algebra','Lloyd N. Trefethen, David Bau III','核心理论','线性代数、数值误差基础',15,'https://epubs.siam.org/doi/book/10.1137/1.9780898719574');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(16,'optimization','Introduction to Applied Linear Algebra: Vectors, Matrices, and Least Squares','Stephen Boyd, Lieven Vandenberghe','基础入门','基础代数与向量运算',16,'https://web.stanford.edu/~boyd/vmls/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(17,'optimization','Convex Optimization','Stephen Boyd, Lieven Vandenberghe','核心理论','线性代数、多元微积分',17,'https://web.stanford.edu/~boyd/cvxbook/');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(18,'discrete-foundations','Discrete Mathematics: An Open Introduction','Oscar Levin','基础入门','高中代数与基本逻辑',18,'https://discrete.openmathbooks.org/dmoi3.html');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES(19,'discrete-foundations','Graph Theory','Reinhard Diestel','进阶学习','基础图论与严格证明方法',19,'https://diestel-graph-theory.com/');

-- Parallel recommendations are alternatives, not translations of one another.
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('100','analysis','数学分析（上、下册）','华东师范大学数学科学学院','基础入门','高中数学、基本证明方法','1','https://xuanshu.hep.com.cn/front/bookFair/findBookFairDetails?onlineBookFairId=68edea3be4b0409c268236e8&timeType=1');
INSERT OR IGNORE INTO learning_book_details VALUES(100,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('101','analysis','实变函数与泛函分析基础','程其襄、张奠宙、胡善文、薛以锋','核心理论','数学分析、线性代数','2','https://xuanshu.hep.com.cn/front/book/findBookDetails?bookId=5bc22d7ff18f967ee7f37832');
INSERT OR IGNORE INTO learning_book_details VALUES(101,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('102','analysis','实分析与泛函分析（续论）','匡继昌','进阶学习','测度与积分、泛函分析基础','3','https://academic.hep.com.cn/im/CN/book/978-7-04-041285-7');
INSERT OR IGNORE INTO learning_book_details VALUES(102,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('103','geometry-topology','微分几何','陈维桓','基础入门','多元微积分、线性代数','1','https://math.pku.edu.cn/jsdw/ltx/141174.htm');
INSERT OR IGNORE INTO learning_book_details VALUES(103,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('104','geometry-topology','微分几何引论','陈维桓','核心理论','曲线曲面、点集拓扑','2','https://xuanshu.hep.com.cn/front/h5Mobile/bookDetails?bookId=59ceb30bba9eb884cf81e34c');
INSERT OR IGNORE INTO learning_book_details VALUES(104,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('105','geometry-topology','黎曼几何选讲','伍鸿熙、陈维桓','进阶学习','微分流形、黎曼度量与联络','3','https://academic.hep.com.cn/attached/file/20200114/20200114155032_409.pdf');
INSERT OR IGNORE INTO learning_book_details VALUES(105,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('106','algebra','高等代数','北京大学数学系；王萼芳、石生明','基础入门','高中代数、基本证明方法','1','https://2d.hep.com.cn/585562293/3');
INSERT OR IGNORE INTO learning_book_details VALUES(106,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('107','algebra','近世代数基础','张禾瑞','核心理论','高等代数、集合与映射','2','https://2d.hep.com.cn/585562293/3');
INSERT OR IGNORE INTO learning_book_details VALUES(107,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('108','algebra','交换代数基础','冯克勤','进阶学习','群、环、域与模论基础','3','https://academic.hep.com.cn/fmc/CN/book/972048');
INSERT OR IGNORE INTO learning_book_details VALUES(108,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('109','number-theory','初等数论（I）','陈景润','基础入门','整数运算、基本证明方法','1','https://hitpress.hit.edu.cn/_upload/article/files/93/8f/d0b0540e426590e8894d3517cc43/34d437f0-b1e7-4850-b48d-678f8ea659a8.pdf');
INSERT OR IGNORE INTO learning_book_details VALUES(109,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('110','number-theory','初等数论（II）','陈景润','核心理论','整除、同余与初等数论基础','2','https://hitpress.hit.edu.cn/_upload/article/files/93/8f/d0b0540e426590e8894d3517cc43/34d437f0-b1e7-4850-b48d-678f8ea659a8.pdf');
INSERT OR IGNORE INTO learning_book_details VALUES(110,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('111','number-theory','代数数论','潘承彪、潘承洞','进阶学习','初等数论、群环域基础','3','https://hitpress.hit.edu.cn/_upload/article/files/93/8f/d0b0540e426590e8894d3517cc43/34d437f0-b1e7-4850-b48d-678f8ea659a8.pdf');
INSERT OR IGNORE INTO learning_book_details VALUES(111,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('112','probability-statistics','概率论与数理统计','孙艳、成丽波、施三支、马文联、王姝娜','基础入门','微积分、组合计数','1','https://xuanshu.hep.com.cn/front/book/findBookDetails?bookId=5fa6dd125710f1bcc39a1afe');
INSERT OR IGNORE INTO learning_book_details VALUES(112,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('113','probability-statistics','概率论（上册）','李增沪、张梅、何辉','核心理论','概率基础、数学分析','2','https://xuanshu.hep.com.cn/front/book/findBookDetails?bookId=66d3513a74ce561611bda71d');
INSERT OR IGNORE INTO learning_book_details VALUES(113,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('114','probability-statistics','概率论（下册）','李增沪、张梅、何辉','进阶学习','概率论、测度与条件期望','3','https://xuanshu.hep.com.cn/front/book/findBookDetails?bookId=686566dce119ac9729118499');
INSERT OR IGNORE INTO learning_book_details VALUES(114,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('115','computational','数值分析','李庆扬、王能超、易大义','基础入门','微积分、线性代数、基础编程','1','https://www.tup.tsinghua.edu.cn/booksCenter/book_02573106.html');
INSERT OR IGNORE INTO learning_book_details VALUES(115,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('116','computational','数值线性代数','徐树方、高立、张平文','核心理论','线性代数、数值误差基础','2','https://math.pku.edu.cn/bks/sykc/148696.htm');
INSERT OR IGNORE INTO learning_book_details VALUES(116,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('117','computational','控制论中的矩阵计算','徐树方','进阶学习','数值线性代数、微分方程基础','3','https://academic.hep.com.cn/engi/CN/book/978-7-04-031611-7');
INSERT OR IGNORE INTO learning_book_details VALUES(117,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('118','optimization','数学模型','姜启源、谢金星、叶俊','基础入门','微积分、线性代数','1','https://abook.hep.com.cn/12396213');
INSERT OR IGNORE INTO learning_book_details VALUES(118,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('119','optimization','最优化方法','孙文瑜、徐成贤、朱德通、孙海琳','核心理论','线性代数、多元微积分','2','https://xuanshu.hep.com.cn/front/book/findBookDetails?bookId=66f2f13ae4efbc722ba484ae');
INSERT OR IGNORE INTO learning_book_details VALUES(119,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('120','optimization','运筹学','刁在筠、戎晓霞、王光辉、刘丙强、刘桂真','进阶学习','线性规划、优化建模与算法基础','3','https://xuanshu.hep.com.cn/front/bookFair/findBookFairDetails?onlineBookFairId=68edea3be4b0409c268236e8&timeType=1');
INSERT OR IGNORE INTO learning_book_details VALUES(120,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('121','discrete-foundations','离散数学','左孝凌、李为鑑、刘永才','基础入门','高中代数、基础逻辑','1','https://mooc.s.ecust.edu.cn/course/441650000016973.html?articleId=139610&edit=false');
INSERT OR IGNORE INTO learning_book_details VALUES(121,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('122','discrete-foundations','组合数学','金应烈、郭强辉、孙慧','核心理论','离散数学、组合计数与证明方法','2','https://xuanshu.hep.com.cn/front/bookFair/findBookFairDetails?onlineBookFairId=68edea3be4b0409c268236e8&timeType=1');
INSERT OR IGNORE INTO learning_book_details VALUES(122,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('123','discrete-foundations','图论及其应用','张先迪、李正良','进阶学习','基础图论、线性代数与严格证明方法','3','https://xuanshu.hep.com.cn/front/book/findBookDetails?bookId=59cc3a9dba9eb884cf816334');
INSERT OR IGNORE INTO learning_book_details VALUES(123,'zh');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('200','number-theory','Algebraic Number Theory','Jürgen Neukirch','进阶学习','初等数论、交换代数基础','3','https://link.springer.com/book/10.1007/978-3-662-03983-0');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('201','probability-statistics','Probability with Martingales','David Williams','核心理论','概率基础、测度与积分','2','https://www.cambridge.org/highereducation/books/probability-with-martingales/B4CFCE0D08930FB46C6E93E775503926');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('202','computational','Numerical Approximation of Partial Differential Equations','Alfio Quarteroni, Alberto Valli','进阶学习','数值分析、偏微分方程与泛函分析基础','3','https://link.springer.com/book/10.1007/978-3-540-85268-1');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('203','optimization','Numerical Optimization','Jorge Nocedal, Stephen J. Wright','进阶学习','凸优化、多元微积分与数值线性代数','3','https://link.springer.com/book/10.1007/978-0-387-40065-5');
INSERT OR IGNORE INTO learning_books(id,direction,title,authors,stage,prerequisites,sort_order,source_url) VALUES('204','discrete-foundations','Concrete Mathematics','Ronald L. Graham, Donald E. Knuth, Oren Patashnik','核心理论','离散数学、组合计数与基本微积分','2','https://cs.stanford.edu/~knuth/gkp.html');
COMMIT;
